Fix: double helps will be displayed if at least one argument is given but none of them are valid (#96)
When we run `cpc` with something like `--qwert` or `--capyright` (the
situation as the title metioned), it will display:

```
Usage:
(......)
Error: extra arguments: (the first invalid extra argument)
Usage:
(......)
```

This is because our program outputs the first help when it doesn't find
valid argument,
then, the program checks if there's extra argument. It will output the
second help message if there is.

It is not necessary to output the two same helps. In this PR, I fix this
bug: through adding a `goto error;` after printing "the first help".
This skips the label `end` and directly return `-1`.

However there's a side effect. When there's no argument provided, it
returns 0 before; but this PR turns it to return -1. Maybe we need to
avoid this side effect?

* Add `goto error;` after printing help